import type { AiAvailability } from '../../editor-ai/contract';
import type { SettingsData } from '../settings';
import type { JsMode } from './js-mode';
import type { CssByMode, EditorCssMode } from './css-mode';

export type AppConfig = {
  post_id: number;
  initialHtml: string;
  initialCustomHead?: string;
  initialCss: string;
  initialCssByMode?: CssByMode;
  initialEditorMode?: EditorCssMode;
  initialJs: string;
  initialJsMode?: JsMode;
  canEditJs: boolean;
  documentHtmlAttributes: string;
  previewUrl: string;
  iframePreviewUrl?: string;
  restUrl: string;
  restCompileUrl: string;
  revisionsRestUrl: string;
  setupRestUrl: string;
  settingsRestUrl: string;
  settingsData: SettingsData;
  legacyCodeVisibilityFallback?: 'code_visible' | 'code_hidden';
  initialEntryMode?: 'ai' | 'blank' | '';
  layoutStorageNamespace?: string;
  backUrl?: string;
  listUrl?: string;
  listLabel?: string;
  tailwindEnabled?: boolean;
  setupRequired?: boolean;
  restNonce: string;
  revisionsSupported?: boolean;
  wpVersion?: string;
  canUpdateCore?: boolean;
  updateCoreUrl?: string;
  adminTitleSeparators?: string[];
  ai?: AiAvailability;
};
