import type { SettingsData } from '../settings';
import type { JsMode } from './js-mode';

export type AppConfig = {
  post_id: number;
  initialHtml: string;
  initialCustomHead?: string;
  initialCss: string;
  initialJs: string;
  initialJsMode?: JsMode;
  canEditJs: boolean;
  documentHtmlAttributes: string;
  previewUrl: string;
  iframePreviewUrl?: string;
  restUrl: string;
  restCompileUrl: string;
  setupRestUrl: string;
  templateCatalogRestUrl?: string;
  importRestUrl?: string;
  settingsRestUrl: string;
  settingsData: SettingsData;
  defaultEditorLayout?: 'code_visible' | 'code_hidden';
  backUrl?: string;
  listUrl?: string;
  listLabel?: string;
  tailwindEnabled?: boolean;
  setupRequired?: boolean;
  restNonce: string;
  adminTitleSeparators?: string[];
};
