import { describe, expect, it } from 'vitest';
import {
  escapeTextForHtml,
  getEditableElementAttributes,
  getEditableTextSegments,
  getElementActionInfo,
  getElementContext,
  getImageSourceEditInfo,
  isSafeEditableElementHtml,
} from '../../../src/admin/element-text';

describe('isSafeEditableElementHtml', () => {
  it('allows plain text and completed inline HTML', () => {
    expect(isSafeEditableElementHtml('Keep your AI-made landing pages')).toBe(true);
    expect(isSafeEditableElementHtml('2 < 3')).toBe(true);
    expect(
      isSafeEditableElementHtml(
        'Keep your AI-made landing pages <span class="text-gradient">inside WordPress.</span>'
      )
    ).toBe(true);
    expect(isSafeEditableElementHtml('Line one<br>Line two')).toBe(true);
    expect(isSafeEditableElementHtml('Text <!-- note --> more text')).toBe(true);
  });

  it('rejects incomplete or unsupported element HTML', () => {
    expect(isSafeEditableElementHtml('<span class="')).toBe(false);
    expect(isSafeEditableElementHtml('<span class="text-gradient">')).toBe(false);
    expect(isSafeEditableElementHtml('<span>inside')).toBe(false);
    expect(isSafeEditableElementHtml('<script>alert(1)</script>')).toBe(false);
    expect(isSafeEditableElementHtml('<strong>inside</strong>')).toBe(false);
    expect(isSafeEditableElementHtml('<div>inside</div>')).toBe(false);
  });
});

describe('getElementContext', () => {
  it('uses descendant text for selected element context', () => {
    const html = [
      '<section data-kayzart-id="section-1" class="testimonials">',
      '  <article>',
      '    <div class="testimonial-card__head">',
      '      <div>',
      '        <p class="testimonial-card__name">50代・女性</p>',
      '        <p class="testimonial-card__meta">ご家族で利用</p>',
      '      </div>',
      '      <p class="testimonial-card__rate">★★★★★</p>',
      '    </div>',
      '  </article>',
      '</section>',
    ].join('\n');

    const context = getElementContext(html, 'section-1');

    expect(context?.text).toBe('50代・女性 ご家族で利用 ★★★★★');
  });

  it('returns null text when selected element has no descendant text', () => {
    const html = '<div data-kayzart-id="empty-1"><img src="example.jpg" alt=""></div>';

    const context = getElementContext(html, 'empty-1');

    expect(context?.text).toBeNull();
  });
});

describe('getEditableTextSegments', () => {
  it('returns direct heading text and span text as separate segments', () => {
    const html = [
      '<h1 data-kayzart-id="heading-1" class="mt-5 text-4xl font-extrabold">',
      '  Keep your AI-made landing pages <span class="text-gradient">inside WordPress.</span>',
      '</h1>',
    ].join('\n');

    const segments = getEditableTextSegments(html, 'heading-1');

    expect(segments).toEqual([
      expect.objectContaining({
        id: 'text-1',
        text: 'Keep your AI-made landing pages',
        labelHint: 'Heading',
      }),
      expect.objectContaining({
        id: 'text-2',
        text: 'inside WordPress.',
        labelHint: 'Text',
      }),
    ]);
  });

  it('expands inline wrapper selections to the parent text group', () => {
    const html = [
      '<h1 data-kayzart-id="heading-1" class="mt-5 text-4xl font-extrabold">',
      '  Keep your AI-made landing pages <span data-kayzart-id="span-1" class="text-gradient">inside WordPress.</span>',
      '</h1>',
    ].join('\n');

    const segments = getEditableTextSegments(html, 'span-1');

    expect(segments.map((segment) => segment.text)).toEqual([
      'Keep your AI-made landing pages',
      'inside WordPress.',
    ]);
  });

  it('matches preview generated ids from the body of a full HTML document', () => {
    const html = [
      '<!doctype html>',
      '<html>',
      '<head><title>Kayzart</title><style>.cta { color: blue; }</style></head>',
      '<body>',
      '<section>',
      '<h1>Keep your AI-made landing pages <span>inside WordPress.</span></h1>',
      '<p>Paste HTML, CSS, and JavaScript generated by ChatGPT.</p>',
      '<a href="/download">Download Free WordPress Plugin</a>',
      '<a href="#how-it-works">See How It Works</a>',
      '</section>',
      '</body>',
      '</html>',
    ].join('');

    const segments = getEditableTextSegments(html, 'kayzart-4');

    expect(segments.map((segment) => segment.text)).toEqual([
      'Paste HTML, CSS, and JavaScript generated by ChatGPT.',
    ]);
  });

  it('keeps preview ids aligned when skipped text tags appear before the selected element', () => {
    const html = [
      '<!doctype html>',
      '<html>',
      '<body>',
      '<section>',
      '<h1>Keep your AI-made landing pages <span>inside WordPress.</span></h1>',
      '<svg><text>Icon label</text></svg>',
      '<p>Paste HTML, CSS, and JavaScript generated by ChatGPT.</p>',
      '<div><a href="/download">Download Free WordPress Plugin</a><a href="#how-it-works">See How It Works</a></div>',
      '</section>',
      '</body>',
      '</html>',
    ].join('');

    const segments = getEditableTextSegments(html, 'kayzart-6');

    expect(segments.map((segment) => segment.text)).toEqual([
      'Paste HTML, CSS, and JavaScript generated by ChatGPT.',
    ]);
  });

  it('returns button text while skipping svg content', () => {
    const html = [
      '<a data-kayzart-id="button-1" class="cta-button" href="/contact">',
      '  <svg><text>Icon label</text></svg>',
      '  <span>無料相談する</span>',
      '</a>',
    ].join('\n');

    const segments = getEditableTextSegments(html, 'button-1');

    expect(segments).toHaveLength(1);
    expect(segments[0]).toEqual(
      expect.objectContaining({
        id: 'text-1',
        text: '無料相談する',
        labelHint: 'Button text',
      })
    );
  });

  it('skips script style svg template and whitespace-only text', () => {
    const html = [
      '<div data-kayzart-id="block-1">',
      '  <script>const label = "Skip";</script>',
      '  <style>.label::before { content: "Skip"; }</style>',
      '  <svg><text>Skip</text></svg>',
      '  <template>Skip template</template>',
      '  <span>Keep me</span>',
      '</div>',
    ].join('\n');

    const segments = getEditableTextSegments(html, 'block-1');

    expect(segments.map((segment) => segment.text)).toEqual(['Keep me']);
  });

  it('keeps an empty selected text element editable', () => {
    const html = '<h2 data-kayzart-id="heading-1"></h2>';
    const offset = html.indexOf('</h2>');

    const segments = getEditableTextSegments(html, 'heading-1');

    expect(segments).toEqual([
      expect.objectContaining({
        id: 'text-1',
        text: '',
        startOffset: offset,
        endOffset: offset,
        labelHint: 'Heading',
      }),
    ]);
  });

  it('keeps a whitespace-only selected text element editable', () => {
    const html = '<span data-kayzart-id="span-1">   </span>';

    const segments = getEditableTextSegments(html, 'span-1');

    expect(segments).toEqual([
      expect.objectContaining({
        id: 'text-1',
        text: '',
        labelHint: 'Text',
      }),
    ]);
  });

  it('does not add an empty text segment for media-only elements', () => {
    const html = '<div data-kayzart-id="block-1"><img src="example.jpg" alt=""></div>';

    const segments = getEditableTextSegments(html, 'block-1');

    expect(segments).toEqual([]);
  });
});

describe('escapeTextForHtml', () => {
  it('escapes markup-looking text so it is saved as text', () => {
    expect(escapeTextForHtml('<strong>A&B</strong>')).toBe(
      '&lt;strong&gt;A&amp;B&lt;/strong&gt;'
    );
  });
});

describe('getElementActionInfo', () => {
  it('detects regular links', () => {
    const html = '<a data-kayzart-id="link-1" href="/contact">Contact</a>';

    expect(getElementActionInfo(html, 'link-1')).toEqual({
      actionLcId: 'link-1',
      kind: 'link',
      tagName: 'a',
      href: '/contact',
      targetBlank: false,
      rel: '',
      disabled: false,
    });
  });

  it('detects button-like links', () => {
    const html = '<a data-kayzart-id="button-1" class="cta-button" href="/contact">Contact</a>';

    expect(getElementActionInfo(html, 'button-1')).toEqual(
      expect.objectContaining({
        actionLcId: 'button-1',
        kind: 'button',
        tagName: 'a',
        href: '/contact',
      })
    );
  });

  it('detects disabled buttons', () => {
    const html = '<button data-kayzart-id="button-1" disabled>Send</button>';

    expect(getElementActionInfo(html, 'button-1')).toEqual(
      expect.objectContaining({
        actionLcId: 'button-1',
        kind: 'button',
        tagName: 'button',
        disabled: true,
      })
    );
  });

  it('ignores regular text elements', () => {
    expect(getElementActionInfo('<p data-kayzart-id="text-1">Hello</p>', 'text-1')).toBeNull();
    expect(getElementActionInfo('<div data-kayzart-id="block-1">Hello</div>', 'block-1')).toBeNull();
  });

  it('uses the nearest parent link action for nested label elements', () => {
    const html =
      '<a data-kayzart-id="link-1" href="/buy" target="_blank" rel="nofollow"><span data-kayzart-id="label-1">Buy</span></a>';

    const info = getElementActionInfo(html, 'label-1');
    const attrsInfo = info ? getEditableElementAttributes(html, info.actionLcId) : null;

    expect(info).toEqual({
      actionLcId: 'link-1',
      kind: 'link',
      tagName: 'a',
      href: '/buy',
      targetBlank: true,
      rel: 'nofollow',
      disabled: false,
    });
    expect(attrsInfo?.tagName).toBe('a');
    expect(attrsInfo?.attributes).toEqual(
      expect.arrayContaining([expect.objectContaining({ name: 'href', value: '/buy' })])
    );
  });

  it('uses the nearest parent button action for nested label elements', () => {
    const html =
      '<button data-kayzart-id="button-1" disabled><span data-kayzart-id="label-1">Send</span></button>';

    const info = getElementActionInfo(html, 'label-1');
    const attrsInfo = info ? getEditableElementAttributes(html, info.actionLcId) : null;

    expect(info).toEqual(
      expect.objectContaining({
        actionLcId: 'button-1',
        kind: 'button',
        tagName: 'button',
        disabled: true,
      })
    );
    expect(attrsInfo?.tagName).toBe('button');
    expect(attrsInfo?.attributes).toEqual(
      expect.arrayContaining([expect.objectContaining({ name: 'disabled', value: '' })])
    );
  });

  it('uses generated parent action ids for nested CTA labels', () => {
    const html = '<a class="cta-button" href="/buy"><span>Buy</span></a>';

    expect(getElementActionInfo(html, 'kayzart-2')).toEqual(
      expect.objectContaining({
        actionLcId: 'kayzart-1',
        kind: 'button',
        tagName: 'a',
        href: '/buy',
      })
    );
  });
});

describe('getImageSourceEditInfo', () => {
  it('returns only the src value range for a selected image', () => {
    const html = '<img data-kayzart-id="image-1" src="old.jpg" alt="Sample">';
    const info = getImageSourceEditInfo(html, 'image-1');
    const from = html.indexOf('old.jpg');

    expect(info).toEqual({
      startOffset: from,
      endOffset: from + 'old.jpg'.length,
      insertPrefix: '',
      insertSuffix: '',
    });
  });

  it('returns an insertion point when the selected image has no src', () => {
    const html = '<img data-kayzart-id="image-1" alt="Sample">';
    const info = getImageSourceEditInfo(html, 'image-1');
    const offset = html.indexOf('>');

    expect(info).toEqual({
      startOffset: offset,
      endOffset: offset,
      insertPrefix: ' src="',
      insertSuffix: '"',
    });
  });

  it('returns an empty value range when the selected image has an empty src', () => {
    const html = '<img data-kayzart-id="image-1" src="" alt="Sample">';
    const info = getImageSourceEditInfo(html, 'image-1');
    const offset = html.indexOf('""') + 1;

    expect(info).toEqual({
      startOffset: offset,
      endOffset: offset,
      insertPrefix: '',
      insertSuffix: '',
    });
  });

  it('returns null for non-image elements and unknown ids', () => {
    const html = '<section data-kayzart-id="section-1"><img src="old.jpg"></section>';

    expect(getImageSourceEditInfo(html, 'section-1')).toBeNull();
    expect(getImageSourceEditInfo(html, 'missing')).toBeNull();
  });
});
